version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code

#    depends_on:
#      - db
    environment:
      - FLASK_ENV=development
 #     - DATABASE_URL="postgres://root:example@db"

#
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: "example"
#      POSTGRES_USER: "root"